[project]
name = "Video Downloader"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "Evalie Studio", email = "contact@evaliestudio.com" }
]
dependencies = [
  "flet==0.26.0",
  "yt_dlp ==2025.1.26",
]

[tool.flet]
# org name in reverse domain name notation, e.g. "com.mycompany".
# Combined with project.name to build bundle ID for iOS and Android apps
org = "com.evaliestudio"

# project display name that is used as an app title on Android and iOS home screens,
# shown in window titles and about app dialogs on desktop.
product = "Video Downloader"

# company name to display in about app dialogs
company = "Evalie Studio"

# copyright text to display in about app dialogs
copyright = "Copyright (C) 2025 by Evalie Studio"

[tool.flet.app]
path = "src"

[tool.uv]
dev-dependencies = [
    "flet[all]==0.26.0",
    "yt_dlp ==2025.1.26",
]

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
flet = {extras = ["all"], version = "0.26.0"}